const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const personajeSchema = new Schema({
  nombre: { type: String, required: true },
  juego: { type: mongoose.Types.ObjectId, ref: "Juego" },
  detallesJuego: { type: String },
  estado: { type: String },
  autor: { type: String },
  propietario: { type: mongoose.Types.ObjectId, ref: "Usuario", required: true },
  imagen: { type: String, required: true },
  cloudinary_id: { type: String },
  trasfondo: [{ type: mongoose.Types.ObjectId, ref: "Trasfondo" }],
  otrosTrasfondos:[{  type: mongoose.Types.ObjectId, ref: "Trasfondo" }],
  edad: { type: Number },
  genero: { type: String },
  idiomas: { type: String },
  lugarNacimiento: { type: String },
  lugarResidencia: { type: String }, 
  peso: { type: String },       //15
  raza: { type: String },
  colorOjos: { type: String },
  colorPelo: { type: String },
  colorPiel: { type: String },
  gafas: { type: String },
  lentillas: { type: String },
  formaCara: { type: String },
  rasgosDistintivos: { type: String },
  estiloVestimenta: { type: String },
  habitos: { type: String },
  aficiones: { type: String },
  refranFavorito: { type: String },
  formaHablar: { type: String },
  enfermedades: { type: String },
  alergias: { type: String },   //30
  minusvalias: { type: String },
  socioeconomiaPeque: { type: String },
  socioeconomiaActual: { type: String },
  manias: { type: String }, 
  tics: { type: String },
  estudios: { type: String },
  trabajo: { type: String },
  mascotas: { type: String },
  monturas: { type: String },
  mayorDefecto: { type: String },
  mayorVirtud: { type: String },
  mayorSecreto: { type: String },
  metasLargoPlazo: { type: String },
  loQueMasImporta: { type: String }, 
  puntoFuerte: { type: String },     //45
  puntoDebil: { type: String },
  manejoIra: { type: Number },
  manejoTristeza: { type: Number },
  manejoConflictos: { type: Number },
  adaptacionCambios: { type: Number },
  adaptacionPerdidas: { type: Number },
  motivaciones: { type: String },
  miedos: { type: String },
  queLeHaceFeliz: { type: String },    
  nivelEmpatia: { type: Number },
  religion: { type: String },
  creenciasEspirituales: { type: Number },
  padre: { type: String },
  madre: { type: String },
  hermanos: { type: String },     //60
  pareja: { type: String },
  hijos: { type: String },
  amigos: { type: String },
  vecinos: { type: String },
  enemigos: { type: String },      //65
});
module.exports = Personaje = mongoose.model("Personaje", personajeSchema);
